name: Build and deploy Python app to Azure Web App - sonarag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write  # Required for JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBC14F7FB01B478CBF89DCB1E01D4EAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE5314B66CE243788E3C87D1CA67BF50 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F0D16FC048744EBB165E337AB453599 }}

      - name: Set Run-From-Package
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sonarag'
          slot-name: 'Production'
          package: '.'   # Deploy current directory
          configuration-file: ''  # Optional
          enable-oryx-build: true
          run-from-package: true   # Enables Run-From-Package

      - name: Restart Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name sonarag --resource-group <YOUR_RESOURCE_GROUP>
